### ISSUE TITLE
Base the container on ubuntu or debian instead of Fedora?

### ISSUE THREAD

**Issue by julien-duponchelle** [gcasella/gns3-docker#2]
Part of current complexity and container size is due to the need of compiling stuff

For ubuntu/debian we have package on a PPA for all the dependencies (VPCS, ubridge, dynamips):
https://gns3.com/support/docs/linux-installation

See also how we build the GNS3 VM:
https://github.com/GNS3/gns3-vm/blob/master/config/install.sh

**Comment by gcasella** [comment]
Hey @noplay,
I chose Fedora primarily due to personal preference.
I also have plans to creating my own repository to package iouyap, ubridge and dynamips. 

I didn't compile VPCS it is only the binary file. 

I'll take a look into a debian based release of the Docker Container as well. 

Note: Github is a new beast for me all together, need to learn this thing via my linux system :)

**Comment by julien-duponchelle** [comment]
Stuff move fast :P The situation already changed since yesterday

A Fedora packager started the packaging:
https://gns3.com/discussions/gns3-package-fedora-24

You can probably join your efforts.

**Comment by gcasella** [comment]
@noplay I was able to reduce the total size of this Docker Container by approximately 500MB. 

I'm looking at other ways that I can reduce the side and remove any other unused packages.

**Comment by gcasella** [comment]
@noplay 
Looking at your install.sh it's only based on Ubuntu 14. I'm looking to test this out on the latest version of Ubuntu.

Update: Nevermind saw it on the gns3.com website to use 
deb http://ppa.launchpad.net/gns3/ppa/ubuntu xenial main
deb-src http://ppa.launchpad.net/gns3/ppa/ubuntu xenial main

**Comment by gcasella** [comment]
@noplay 
GNS3 Docker version of ubuntu 16.04 has been created. 
https://github.com/gcasella/gns3-docker/tree/master/ubuntu-dev
https://hub.docker.com/r/gcasella/gns3-docker/tags/ (gcasella/gns3-docker:ubuntu) ~850mb after extracted
